// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tvwhdgbtahtbaaedvlnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2d2hkZ2J0YWh0YmFhZWR2bG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTUyMzEsImV4cCI6MjA2NjkzMTIzMX0.ziA9-XZzzPUo1vizZ4dqoySqQvnotrZcYmcTOGpwgZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);